import { jsPDF } from 'jspdf';
import type Konva from 'konva';
import type { PedigreeMetadata } from '../types/pedigree';

const MARGIN = 20;
const HEADER_FONT_SIZE = 16;
const BODY_FONT_SIZE = 10;
const FOOTER_FONT_SIZE = 8;

export async function exportToPdf(
  stage: Konva.Stage,
  metadata: PedigreeMetadata
): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Header ---
  let cursorY = MARGIN;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(HEADER_FONT_SIZE);
  doc.text(metadata.title, MARGIN, cursorY);
  cursorY += 7;

  // Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(BODY_FONT_SIZE);
  const dateStr = new Date(metadata.updatedAt).toLocaleDateString();
  doc.text(`Date: ${dateStr}`, MARGIN, cursorY);
  cursorY += 5;

  // Author / Institution
  if (metadata.author) {
    doc.text(`Author: ${metadata.author}`, MARGIN, cursorY);
    cursorY += 5;
  }
  if (metadata.institution) {
    doc.text(`Institution: ${metadata.institution}`, MARGIN, cursorY);
    cursorY += 5;
  }

  // Horizontal rule
  cursorY += 2;
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, cursorY, pageWidth - MARGIN, cursorY);
  cursorY += 5;

  // --- Stage image ---
  const dataUrl = stage.toDataURL({ pixelRatio: 3, mimeType: 'image/png' });

  const availableWidth = pageWidth - MARGIN * 2;
  const footerHeight = 15;
  const availableHeight = pageHeight - cursorY - footerHeight;

  // Calculate dimensions preserving aspect ratio
  const stageWidth = stage.width();
  const stageHeight = stage.height();
  const scale = Math.min(
    availableWidth / stageWidth,
    availableHeight / stageHeight
  );
  const imgWidth = stageWidth * scale;
  const imgHeight = stageHeight * scale;

  // Center horizontally
  const imgX = MARGIN + (availableWidth - imgWidth) / 2;

  doc.addImage(dataUrl, 'PNG', imgX, cursorY, imgWidth, imgHeight);

  // --- Footer ---
  const footerY = pageHeight - MARGIN / 2;
  doc.setFontSize(FOOTER_FONT_SIZE);
  doc.setTextColor(120, 120, 120);

  const footerLeft = 'Generated by Pedigree Editor';
  const footerRight = new Date().toLocaleDateString();

  doc.text(footerLeft, MARGIN, footerY);
  doc.text(footerRight, pageWidth - MARGIN, footerY, { align: 'right' });

  // --- Save ---
  doc.save(`${metadata.title}.pdf`);
}
